CREATE TABLE IF NOT EXISTS market(
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
    name TEXT NOT NULL UNIQUE,
    location TEXT NOT NULL,
    vendors INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);