CREATE TABLE IF NOT EXISTS orders(
    id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    buyerid UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    products JSON NOT NULL,
    riderid UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    status TEXT
);